spring:
  application:
    name: videostorageservice

sqs:
  queue:
    name: ${SQS_QUEUE_NAME}
s3:
  bucket:
    name: ${S3_BUCKET_NAME}
videomanagementservice:
  url: ${VIDEO_MANAGEMENT_URL}

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
server:
  servlet:
    context-path: /storage-service